import { 
  Sun, 
  Moon, 
  Sparkles, 
  Egg, 
  Coffee, 
  Dumbbell, 
  Utensils, 
  Footprints, 
  Ban, 
  Bed,
  Check,
  X,
  ChevronRight,
  ChevronLeft,
  Settings,
  Calendar,
  BarChart3,
  Home,
  Timer,
  Play,
  Pause,
  RotateCcw,
  Upload,
  Download,
  AlertCircle,
  CheckCircle2,
  SkipForward,
  MoreVertical,
  Edit3,
  Trash2,
  Plus,
  Minus,
  GripVertical,
  Bell,
  Moon as MoonIcon,
  Sun as SunIcon,
  type LucideIcon
} from 'lucide-react';

export const iconMap: Record<string, LucideIcon> = {
  sun: Sun,
  moon: Moon,
  sparkles: Sparkles,
  egg: Egg,
  coffee: Coffee,
  dumbbell: Dumbbell,
  utensils: Utensils,
  footprints: Footprints,
  ban: Ban,
  bed: Bed,
  check: Check,
  x: X,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  settings: Settings,
  calendar: Calendar,
  barChart3: BarChart3,
  home: Home,
  timer: Timer,
  play: Play,
  pause: Pause,
  rotateCcw: RotateCcw,
  upload: Upload,
  download: Download,
  alertCircle: AlertCircle,
  checkCircle2: CheckCircle2,
  skipForward: SkipForward,
  moreVertical: MoreVertical,
  edit3: Edit3,
  trash2: Trash2,
  plus: Plus,
  minus: Minus,
  gripVertical: GripVertical,
  bell: Bell,
};

export function getIcon(name: string): LucideIcon {
  return iconMap[name] || Sun;
}
